receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:

  logging:
    verbosity: detailed

  otlphttp/loki:
    endpoint: http://loki:3100/otlp/

  prometheus:
    endpoint: 0.0.0.0:8889

  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
      enabled: true

  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

# connectors:
#   spanmetrics:
#     exclude_dimensions: ['status.code']
#     # namespace: span.metrics

processors:
  batch:

  attributes/delete_unused:
    actions:
      - key: otelSpanID
        action: delete
      - key: otelTraceID
        action: delete
      - key: otelTraceSampled
        action: delete
      - key: otelServiceName
        action: delete


extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch]
      # exporters: [debug, otlp/jaeger]
      exporters: [debug, otlp/tempo, otlp/jaeger]
    metrics:
      receivers: [otlp]
      # processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch, attributes/delete_unused]
      exporters: [logging, otlphttp/loki]

    # traces/2:
    #   receivers: [otlp]
    #   exporters: [spanmetrics]
    # metrics/2:
    #   receivers: [spanmetrics]
    #   exporters: [prometheusremotewrite]